toolchain("clang-cl")
    set_kind("standalone")
    set_toolset("cc",  "clang-cl")
    set_toolset("cxx", "clang-cl")
toolchain_end()

target("Euclid")
    set_kind("binary")
    set_languages("c++20")
    set_optimize("aggressive")
    set_warnings("allextra", "error")
    set_toolchains("clang-cl")
    add_cxxflags("-mavx2")
    add_cxxflags("-mfma")
    add_cxxflags("/GS-")
    add_cxxflags("-Wno-pragma-pack")
    add_cxxflags("-Wno-unknown-pragmas")
    add_includedirs("include")
    add_files("tests/Main.cpp")