#pragma once
#include <bit>
#include "Common/Core.hpp"
#include "Common/Math.hpp"
#include <immintrin.h>
#include "Vector.hpp"
#include "Point.hpp"
//#include "Matrix.hpp"
//#include "Transformation.hpp"
//#include "Triangle.hpp"